# TOML comments use hash symbols, not double slashes

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node app.js"